### ISSUE TITLE
Compile error with GCC 10.2.0

### ISSUE THREAD

**Issue by paolodepetrillo** [mirsadm/motioncam#11]
I am compiling with GCC 10.2.0 on Arch Linux. In 8785d935 the (float) cast was removed from sqrt(0.5f) at:
https://github.com/mirsadm/motioncam/blob/d2760442b1d6fc935f2168397749a5d3809dc0f5/libMotionCam/libMotionCam/generators/DenoiseGenerator.cpp#L410 https://github.com/mirsadm/motioncam/blob/d2760442b1d6fc935f2168397749a5d3809dc0f5/libMotionCam/libMotionCam/generators/DenoiseGenerator.cpp#L464 https://github.com/mirsadm/motioncam/blob/d2760442b1d6fc935f2168397749a5d3809dc0f5/libMotionCam/libMotionCam/generators/DenoiseGenerator.cpp#L846

This caused the compile to fail with the error:
DenoiseGenerator.cpp:410:120: error: ambiguous overload for ‘operator*’ (operand types are ‘Halide::Expr’ and ‘double’)

Adding the (float) back in seems to fix it, it compiles and runs.

[fix_compile_error.patch.txt](https://github.com/mirsadm/motioncam/files/6322583/fix_compile_error.patch.txt)

**Comment by mirsadm** [comment]
Cheers, fixed that one.
