### ISSUE TITLE
The converter does not work with AMD FX 8300 CPU

### ISSUE THREAD

**Issue by Gogo1973** [mirsadm/motioncam#112]
The converter does not work with AMD FX processor, with RYZEN no problem, Windows 10 21H2. Am I not doing something right, or do I need something extra?

**Comment by mirsadm** [comment]
It is probably because they are missing some needed CPU instructions. Next time I update the tools I'll recompile it so that it works on older CPUs.

**Comment by Gogo1973** [comment]
Thanks,for everything you have done so far with MotionCam!

**Comment by mirsadm** [comment]
Can you see if this fixes it:
https://github.com/mirsadm/motioncam/releases/download/8.0.6-beta4/motioncam-tools-0.0.4-windows.zip

**Comment by Gogo1973** [comment]
No, same as 0.0.3 doesn't work ...

**Comment by Gogo1973** [comment]
Strangely, the second file started, and both are made with version 8.0.6-beta4

**Comment by mirsadm** [comment]
ah I uploaded it to the same beta which is probably why it seems confusing. great, i'll close this
