### ISSUE TITLE
only 1 audio channel (mono)

### ISSUE THREAD

**Issue by darkblaze69** [mirsadm/motioncam#113]
Recorded video with playmarket 8.0.5 version. I got DNGs with wav file which contains only one audiochannel. But my phone supports stereo audio.
Poco X3 Pro, using custom ROM Android 12.

**Comment by mirsadm** [comment]
https://github.com/mirsadm/motioncam/releases/download/8.0.6-beta5/MotionCam.8.0.6-beta5.apk

Shoud be fixed here

**Comment by Gooner447** [comment]
Checking out stereo on now on beta 5 . recording in both channels but only records first 6 seconds of a 11 second clip and 11 seconds on a 20 second clip, seems to stop recording about half-way into the clip. As ever this is fyi not a complaint,

**Comment by mirsadm** [comment]
Cheers
Will look into this

**Comment by Gooner447** [comment]
👍

**Comment by mirsadm** [comment]
This should be fixed here:
https://github.com/mirsadm/motioncam/releases/download/8.0.6-beta6/MotionCam.8.0.6-beta6.apk

**Comment by darkblaze69** [comment]
great thanks! works as expected
