### ISSUE TITLE
motiontools for applesilicon

### ISSUE THREAD

**Issue by arianamg** [mirsadm/motioncam#121]
is it possible to compile motiontools with universal binary? it's working with rosetta but performance drop is huge (comparable with my i5-4460 pc)
btw is it possible to make the conversion gpu accelerated ?

**Comment by mirsadm** [comment]
@arianamg here you go:
https://github.com/mirsadm/motioncam/releases/download/8.0.7-beta4/motioncam-tools-mac-m1-0.1.1.dmg

In my brief testing the M1 mac is insanely fast

**Comment by mirsadm** [comment]
@arianamg there is now native support for apple silicon.
