### ISSUE TITLE
Smooth focus adjustment

### ISSUE THREAD

**Issue by lordsvarogofmax** [mirsadm/motioncam#122]
Thank you so much for the cool RAW video shooting app!
It would be really cool to add a slider for smooth focus adjustment. 
Tap with your finger works quite sharply and when shooting it does not look very natural. Thank you again very much!

**Comment by mirsadm** [comment]
Thank you! There is a non obvious way to change focus. You can click the X.YY M text next to iso/shutter and it will let you change the focus manually.
