### ISSUE TITLE
NOT WORKING MBA M1 12.1

### ISSUE THREAD

**Issue by MotleyTRIP** [mirsadm/motioncam#132]
NOT WORKING MBA M1 12.1

**Comment by mirsadm** [comment]
what exactly is not working?

**Comment by MotleyTRIP** [comment]
0.1 version still crash when after import try to select for further action!!!

**Comment by mirsadm** [comment]
I've built them for the M1 Mac here:
https://github.com/mirsadm/motioncam/releases/download/8.0.7-beta4/motioncam-tools-mac-m1-0.1.1.dmg

**Comment by MotleyTRIP** [comment]
m1 versión doesn't even start ))))))))))) intel starts but still with above issue

**Comment by Mrdoumhann** [comment]
Thanks for the m1 support. But I couldn't get it to work either. I tested it on M1 Air (Big Sur) and I get the the "application is damaged" error.

**Comment by mirsadm** [comment]
Yep I will fix this soon. Ordering an M1 Mac for testing :)

**Comment by mirsadm** [comment]
Finally got a new M1 MBP. I can reproduce the problem so will fix soon.

**Comment by mirsadm** [comment]
@Mrdoumhann @MotleyTRIP this is now finally fixed in the new betas
