### ISSUE TITLE
[Feature Request] Bluetooth Release Support

### ISSUE THREAD

**Issue by LuckyBastard73** [mirsadm/motioncam#136]
I have a Bluetooth shutter release and that works with virtually every camera app right out of the box.
MotionCam seems to be an exception. Or let's say it does not work as expected. 
I always get a burst and the editing tools no matter in which mode I am.
I would like to get an image if I am in night or normal photo mode.
A burst only if I am in the burst mode.

**Comment by mirsadm** [comment]
Sounds like it works by simulating the volume up/down keys. That'll explain why that happens.

**Comment by LuckyBastard73** [comment]
You are right but why is this not the case for GCam, the stock camera app oder OpenCamera?
I would expect the same behaviour.
On the release there is an large and a small button. 
They behave different, as one takes the burst and the other lets the volume control appear.

**Comment by mirsadm** [comment]
It happens because I wasn't aware that's what most people expected out of the buttons :D I can easily change it to replicate that behaviour

**Comment by experimentator1709** [comment]
@mirsadm 
https://github.com/mirsadm/motioncam/issues/49

**Comment by mirsadm** [comment]
^ This will be fixed in next update.

**Comment by LuckyBastard73** [comment]
I can confirm that the remote shutter release is now working the same way as in most other camera apps in the latest beta.
