### ISSUE TITLE
[RAW Video/Presets] Use slightly larger resolutions if exact ones are unavailable

### ISSUE THREAD

**Issue by epicfilmmaker93** [mirsadm/motioncam#137]
Currently 4K preset on my device sets the resolution to slightly smaller than 4K (3836x2152), which is not ideal because it will require some upscaling on a 4K timeline or some black borders around the image. Same thing happens with the 1080p preset. Would be great if the presets would set the resolution to the one that is slightly bigger than 4K - for example, for my device it is 3884x2186. This way the video can just be cropped a bit and will look good after the export of a 4K project

**Comment by mirsadm** [comment]
Yes it should do, that's a bug.

**Comment by mirsadm** [comment]
@epicfilmmaker93 this one is fixed in latest beta

**Comment by epicfilmmaker93** [comment]
Confirmed, thanks
