### ISSUE TITLE
8.0.7 beta 4 crashes on Google Pixel

### ISSUE THREAD

**Issue by nocantsin** [mirsadm/motioncam#149]
8.0.7 beta 4 crashes on a Google Pixel (6 Pro) with the same symptoms and error message as in the past: After starting the app, the camera display remains black except for the UI elements, and after a few seconds, the app crashes with the pop-up message "Error: The camera encountered an error".

A log file is attached here.

[motion_cam-8.0.7-beta4-crash_log.txt.gz](https://github.com/mirsadm/motioncam/files/7876203/motion_cam-8.0.7-beta4-crash_log.txt.gz)

**Comment by mirsadm** [comment]
Thanks for letting me know. Did the previous beta work? That will narrow down the changes

**Comment by 2blackbar** [comment]
pixel 2xl works fine if that helps

**Comment by mirsadm** [comment]
Did the previous beta work? That's narrow it down

**Comment by nocantsin** [comment]
The previous beta worked!

**Comment by mirsadm** [comment]
Beta 3 is ok? Beta 4 no good? That narrows it down for me I'll sort it out today

**Comment by nocantsin** [comment]
Sorry, was mistaken (tested again). Beta 3 has the same issue, Beta 2 works.

**Comment by mirsadm** [comment]
Ah great know exactly what it is. The Pixel phones seem extremely finicky

**Comment by mirsadm** [comment]
@nocantsin should be fixed now:
https://github.com/mirsadm/motioncam/releases/download/8.0.7-beta5/MotionCam-8.0.7-beta5.apk

**Comment by nocantsin** [comment]
Yes, this version works! So many trhanks for all your great work!

**Comment by mirsadm** [comment]
Excellent :)
