### ISSUE TITLE
Crash of Convert/Export Windows tool

### ISSUE THREAD

**Issue by LuckyBastard73** [mirsadm/motioncam#153]
When I try to open a 19GB clip the converter/exporter on my Windows 10 (21H2, x64) machine (16BG RAM) crashes.
In my case this happened with version 0.1.1.

**Comment by mirsadm** [comment]
Does this happen on all files or just that particular one?

**Comment by LuckyBastard73** [comment]
Only with that file. Next next bigger one I have is only 12GB.
When I star the app in WinDbg I get the following info:
![CrashInfo](https://user-images.githubusercontent.com/76913290/150024330-0cb68e54-39e8-435b-bdc1-7c57eabacfae.jpg)
The crash happens when I press here
![Clipboard02](https://user-images.githubusercontent.com/76913290/150024716-70385b9f-328c-478f-a047-b92be920ccea.jpg)

**Comment by LuckyBastard73** [comment]
To be honest I don't want to stress my phone with the export of such large files.

**Comment by LuckyBastard73** [comment]
I tried the export on a second machine where I copied the file to directly from the phone and here it works.
Maybe the container file got corrupted during the copy process.
So the crash does not seem to happen with regular clips.
An app should not crash in such a situation anyway but as this is not a commercial product this is completely fine.
