### ISSUE TITLE
What about phone storage life?

### ISSUE THREAD

**Issue by GorIvanov** [mirsadm/motioncam#169]
I have tested the app and in is great!
Galaxy s21 ultra.

But  I think you should make able to record directly to a folder that user selects.
I mean, that at first data is stored on the device where the user don't have access, then we do converting to dng.
So, 25-30 seconds video takes 5 Gb memory and + 5 Gb after converting.
So we spent~ 10 Gb for 25 seconds.

If you shoot video often at a professional level, then the smartphone’s drive will simply fail, as there is a resource for overwriting data like on a regular SSD.

So, it would be great to have the possibility to select folder to record data directly.
In this case, it will be possible to connect external SSD or fast SD card to the phone.

Are there any plans to add this feature?

**Comment by mirsadm** [comment]
You can already do this :) in the settings you can choose where to record to
