### ISSUE TITLE
The choice of raw in smartphones Аsus

### ISSUE THREAD

**Issue by Jeneeeeek** [mirsadm/motioncam#181]
Hello, question, many Asus devices have two raw formats at once, please tell me, could you add a switch in the settings. They just have the full resolution of raw, whether it's 48/64mp , as well as the second Raw with 12/16mp binning.
![Screenshot_20220204-130950_MT Manager](https://user-images.githubusercontent.com/96690234/152519312-6be3d987-e070-4198-a8ef-dba90cc4d312.png)
in the screenshot, I showed that there are two Raw permissions at once

**Comment by Jeneeeeek** [comment]
Landroid/hardware/camera2/params/StreamConfigurationMap;->getOutputSizes(I)[Landroid/util/Size;

**Comment by mirsadm** [comment]
I pushed out a new beta that should pick the binned option. At some point in the future I'll add it as an option instead. Let me know if it works.

**Comment by teemodk** [comment]
The beta works. Previously I had a mod to disable high resolution, but that's not needed now. Binning output is chosen for both images and "video".

**Comment by mirsadm** [comment]
Cheers I'll close this for not

**Comment by Jeneeeeek** [comment]
> Ура, я закрою это, чтобы не

Zenfone 7 pro all the same has 64MP raw but doesn't have 16mp bin
