### ISSUE TITLE
S20 FE 4G Snapdragon crashes when switching selfie camera

### ISSUE THREAD

**Issue by Gogo1973** [mirsadm/motioncam#182]
8.0.8-beta 2 application crashes when switching selfie camera. S20 FE SM-G780G.

**Comment by mirsadm** [comment]
I've updated it to remove a change I made to the camera startup sequence:
https://github.com/mirsadm/motioncam/releases/download/8.0.8-beta2/MotionCam.8.0.8-beta3.apk

Let me know if that fixes it

**Comment by Gogo1973** [comment]
continues to close

**Comment by mirsadm** [comment]
This one is priority for me so looking for reason why it's crashing

**Comment by mirsadm** [comment]
@Gogo1973 This is finally fixed in the latest beta
