### ISSUE TITLE
8.0.8 from Google Play: Samsung S20FE4GSD crashed when "Dual Exposure Controls" is activated in the settings

### ISSUE THREAD

**Issue by giteos** [mirsadm/motioncam#184]
After setting the option and going back to the camera view (using the phones "back" button) the app crashes.
Can only be re-activated by deleting cache/files in settings->apps->motion cam->memory.

**Comment by GusevAG** [comment]
Same on samsung note 10 lite Exynos 9810 after upgrading to android 12

**Comment by nashitahmedbarq** [comment]
I have the same issue on Android 12. 

Everything works fine except when I enable dual exposure, the app force stops.

**Comment by mirsadm** [comment]
dual exposure is now enabled by default and should work on all phones. Unfortunately it's not quite as accurate as before but it'll have to do for now
