### ISSUE TITLE
HDR Image Quality

### ISSUE THREAD

**Issue by make-stronger** [mirsadm/motioncam#19]
Hi @mirsadm,

HDR image output in some scenes contain a big white area have more noise.
I think it appear due to you use only single under-exposure frame without denoise and a-part of white area come from under-exposure frame.

**Comment by mirsadm** [comment]
Hey!
Thanks for the feedback. Yes I did notice this myself. It is being too aggressive in trying to recover highlights. I am tweaking it further to avoid situations such as these. I'll create another build soon.
