### ISSUE TITLE
Problem with MotionCam Tool-0.13

### ISSUE THREAD

**Issue by Gogo1973** [mirsadm/motioncam#195]
Problem with MotionCam Tool-0.13, noise reduction creates a mirror strip at the edges. Watch this video: https://www.youtube.com/watch?v=Xtmu0eX4QGc

**Comment by mirsadm** [comment]
Yep it extends the edges during NR but should crop them out when exporting which it is not. I need to do that.

**Comment by nubbie61** [comment]
Hi. I'm having the same issue. Checked it with win-tools-12 - the same result. Looks like the dng file has been saved with this distortion BEFORE the NR from the convertor. Surely the dev would be able to finx it. Otherwise absolutely amazing product! Fantastic good job

**Comment by mirsadm** [comment]
yep that's been fixed, going to push out an update soon

**Comment by nubbie61** [comment]
Great news, really. Thank you very much

**Comment by mirsadm** [comment]
@Gogo1973 this has finally been fixed
