### ISSUE TITLE
Compare with Hdr-plus.

### ISSUE THREAD

**Issue by bxomark** [mirsadm/motioncam#20]
Hi @mirsadm,

Did you make a comparison with hdr-plus ([timothybrooks implemented](https://github.com/timothybrooks/hdr-plus)) on the results of merged raw image?

**Comment by mirsadm** [comment]
No I have not. That is a reimplementation of the original HDR+ paper from Google. This project doesn't really have too much in common with that. Feel free to compare the result, it would be an interesting experiment.
