### ISSUE TITLE
Latest version causes purple color in overexposed areas

### ISSUE THREAD

**Issue by f0enix** [mirsadm/motioncam#21]
Hi,
I have some raw bayer data which i average using _libMotionCam_ binary. It was working fine but today i built the latest version from master branch (commit hash _83a52b7984d58ac8dc895ce02e42f63e31a50975_) and running it on same data, i noticed that all overexposed areas are being displayed as purple.
Here is a preview generated from such raw data:
![frame_8](https://user-images.githubusercontent.com/72214428/127656510-2fe50e42-b155-4ad3-a160-d269f49df359.jpg)

Now if i average it by feeding it as a zip (containing all required metadata) to _libMotionCam_ binary on my mac, this is what i get:
![Archive zip](https://user-images.githubusercontent.com/72214428/127656690-a81e4314-199b-4520-b1e6-abcc7f8069a2.jpg)

i can deduce that the preview functions are working fine, it seems that the post processing is broken and some clipping is occurring in those bright regions. 
Note that same zip which contains multiple frames of this shot with same settings produces good output with earlier versions of libMotionCam binary. I tried with several images and all have this purple color in overexposed regions.

Here is the post processing settings i used:
```json
"postProcessingSettings": {
        "blacks": 0.032499998807907104,
        "contrast": 0.5,
        "flipped": false,
        "noiseSigma": 0,
        "chromaEps": 32,
        "sceneLuminance": 0,
        "spatialDenoiseAggressiveness": 1,
        "temperature": 3678,
        "tonemapVariance": 0.25,
        "whitePoint": 1,
        "sharpen1": 1.2999999523162842,
        "shadows": 4.0658516883850098,
        "blueSaturation": 1,
        "jpegQuality": 98,
        "greenSaturation": 1,
        "saturation": 1,
        "exposure": 0,
        "gamma": 2.2000000476837158,
        "tint": 24,
        "sharpen0": 3.4000000953674316
    }
```

Is this a bug or does the latest version requires shooting dark exposures and needs HDR fusion to fix it?

**Comment by mirsadm** [comment]
are you able to provide the zip file for me? it certinaly looks like a clipping bug

**Comment by f0enix** [comment]
Here is the link to the zip:
[https://www.filemail.com/d/impgbqiqtdkdjfn](https://www.filemail.com/d/impgbqiqtdkdjfn)

**Comment by mirsadm** [comment]
Cheers, I've downloaded it. Will look at it tonight if I can. Feel free to delete it from there.

**Comment by mirsadm** [comment]
That's been fixed in the latest commit. Thanks for reporting that.
