### ISSUE TITLE
Forceclose when enable dual exposure controls.

### ISSUE THREAD

**Issue by backzaa** [mirsadm/motioncam#228]
I have problem in android 12,When enable dual exposure controls and exit setting. app forceclose 😢

*In android 11 no have this problem.

Mi 10 ultra a12 / miui 13

**Comment by nashitahmedbarq** [comment]
Have you tried latest beta 8.1.0-beta2, the problem had been fixed there.

**Comment by backzaa** [comment]
> Have you tried latest beta 8.1.0-beta2, the problem had been fixed there.

It's work. Thank you 😀

**Comment by mirsadm** [comment]
Dual exposure will come back in a better form soon :)
