### ISSUE TITLE
Compile error with GCC 11.1.0

### ISSUE THREAD

**Issue by paolodepetrillo** [mirsadm/motioncam#24]
I am getting a compile error on [this line](https://github.com/mirsadm/motioncam/blob/f9cb533201a04e664d2b541f5c6fc06d594b8e06/libMotionCam/libMotionCam/generators/DenoiseGenerator.cpp#L809):
```
DenoiseGenerator.cpp:809:24: error: ambiguous overload for ‘operator*’ (operand types are ‘double’ and ‘Halide::Expr’)
  809 |     Expr T = sqrt(3.0f)*(Nsig*Nsig) / Ssig(v_x, v_y, v_c, v_i);
      |              ~~~~~~~~~~^~~~~~~~~~~~
      |                  |           |
      |                  double      Halide::Expr
```

Changing sqrt(3.0f) to ((float)sqrt(3.0f)) fixes it.

In the same file there are also a few warnings like this but they don't prevent it from compiling.
```
DenoiseGenerator.cpp:348:30: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<float>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
  348 |         for(int idx = 0; idx < H.size(); idx++) {
      |                          ~~~~^~~~~~~~~~
```

**Comment by mirsadm** [comment]
Thanks, fixed. I'm on a Mac and clang for whatever reason doesn't seem to be as sensisitve.
