### ISSUE TITLE
Is Motion Cam still open source?

### ISSUE THREAD

**Issue by marvellousCodeRanger** [mirsadm/motioncam#250]
Hello, I see that the source code has been removed from the repo, however the license is still GPL-3.0. Does that mean Motion Cam is still open source but we can only get the code if we ask you to provide it or are you going to use some other code distribution model or license for new releases?

**Comment by mirsadm** [comment]
Hi there,
The existing code will continue to be licensed under GPL-3.0 (which you can still find of course). I'm moving the distribution of the app to the Play Store entirely. There will be the free app and a more professional paid app released shortly. I'll keep the GitHub page for reporting issues.

I was hoping to get more support with the development of the app by having it open source on GitHub but unfortunately that hasn't really worked out. Instead I'm going to try this approach moving forward.

Cheers

**Comment by marvellousCodeRanger** [comment]
Ok, thank you for the explanation. The only thing I would ask you is to consider to continue posting the source code of the free app somewhere (maybe in another repo with issues turned off or in this repo with a big disclaimer in the readme.md) so that people could compile the app themselves or just check the source. Other than that, I wish you all the best and I hope a new model will help you to make your app even better
