### ISSUE TITLE
MotionCam Pro - Wrong "White Balance" on OnePlus 9 Pro

### ISSUE THREAD

**Issue by Muckymuckman** [mirsadm/motioncam#251]
On any other version of MotionCam after version 8.0.8 - beta1, there is a problem with white balance. When viewing the DNG with any Camera Raw (on a PC or in Lightroom), you can observe that the Tint slider is shifted to the left edge, with a tinge of purple always present. In dng from MotionCam Pro it is literally impossible to get the white balance right. 
The problem is not repeated in MotionCam 8.0.8 - beta1.
I have attached a couple of screenshots of dng files taken with different versions of MotionCam + 2 dng frames from different versions in the archive.
[dng frames.zip](https://github.com/mirsadm/motioncam/files/8799040/dng.frames.zip)

![MotionCamPro](https://user-images.githubusercontent.com/88900024/171011104-b0aba28d-914f-4f16-a6c8-425216ae8765.jpg)
![MotionCam - 808-beta1](https://user-images.githubusercontent.com/88900024/171011129-d20aecec-10fb-4712-985c-8acc11312614.jpg)

**Comment by Muckymuckman** [comment]
dng frames.zip

**Comment by mirsadm** [comment]
@Muckymuckman thanks for reporting that. Are you able to record a short RAW video and share it? That'll be helpful in finding the issue

**Comment by Muckymuckman** [comment]
@mirsadm 
Done. Attached are two links to archives with recordings
https://drive.google.com/file/d/13D1y2AdtK5VDCOIIKZlVpsgip5N-cLip/view?usp=sharing
https://drive.google.com/file/d/1XRcRRe9A4KtxHYATnslN2x4sdLGRVzPV/view?usp=sharing

**Comment by mirsadm** [comment]
@Muckymuckman thanks for providing those. I have found the reason why the white balance isn't right. Weirdly it seems to be an issue with just LR (Google Photos and my Mac show the correct white balance). Anyway I will push out a fix to correct this hopefully today.

**Comment by Muckymuckman** [comment]
@mirsadm Awesome. Looking forward to it!

**Comment by mirsadm** [comment]
@Muckymuckman thanks again for reporting that issue. I've pushed an update with the fix to the play store. You can contact me directly on Discord if you encounter any issues!
