### ISSUE TITLE
v5 worse dynamic range

### ISSUE THREAD

**Issue by Sergio677** [mirsadm/motioncam#26]
As I understand, v4 uses underexposure and increases shadows. HDR effect in result.

Beginning with v5 there is no hdr. Also, lacks contrast and sharpening (yes, more noise, but overall looks better, crisper).

v4 / v5
![IMG_20211003_060551](https://user-images.githubusercontent.com/91436285/135739245-422c395a-4d67-456d-af98-d5ca2354d463.jpg)
![IMG_20211003_060714](https://user-images.githubusercontent.com/91436285/135739363-34e814db-c520-4a35-8a36-78cf32b4b072.jpg)
![IMG_20211003_061404](https://user-images.githubusercontent.com/91436285/135739972-815d8cbd-9e64-4520-9225-aa11ea8b025c.jpg)
![IMG_20211003_061519](https://user-images.githubusercontent.com/91436285/135740005-c4660e2d-4441-4457-9833-8938df3c1efa.jpg)
 v4 gives fine contrast in night flat scene, crisper. v5 dimmer (also out of focus, for some reason couldn't catch, unlike 4).

**Comment by mirsadm** [comment]
In general I've tried to tone down the amount of processing to make the images look a bit more natural. I will add a setting for sharpness so that it can be adjusted. I've pushed out a new release that increases the aggressiveness of HDR. It's on the releases page now. Let me know if that helps, in general the HDR should be much better than in v4.

**Comment by Sergio677** [comment]
5.0.3 / 5.0.1 / 4.0.0
![IMG_20211005_050050](https://user-images.githubusercontent.com/91436285/135949943-ff63e9ac-c8cf-4abe-85c9-31ecca68ff71.jpg)
![IMG_20211005_050211](https://user-images.githubusercontent.com/91436285/135950125-bab233c8-7692-433a-9f2b-e7fe690aa1c2.jpg)
![IMG_20211005_050326](https://user-images.githubusercontent.com/91436285/135950420-93b4cb75-bc49-4e55-a112-28a5b5c04ebb.jpg)
It's strange but now there is no strong difference between 4 & 5, only cosmetic. Maybe because of iso/shutter are similar in all 3 images. Earlier v4 always underexposed in compare to 5
