### ISSUE TITLE
Add instruction for how build app under Windows

### ISSUE THREAD

**Issue by dimka11** [mirsadm/motioncam#31]
I need build this app under Windows

**Comment by joemarshall** [comment]
You can build it in Windows subsystem for Linux. Just install Ubuntu in wsl and then follow the Ubuntu instructions.

**Comment by dimka11** [comment]
@joemarshall but, how install Android Studio in WSL?

**Comment by joemarshall** [comment]
You could probably install android studio in WSL and run it nowadays (although you lose emulator support that way), but you can build an android studio project by just running the gradlew script in the top of the project (i.e. with only the android sdks/ndks and tools installed, not full android studio)

**Comment by mirsadm** [comment]
I don't have a Windows machine to be able to set this up. It should be possible to get it to work with some effort. Unfortunately I don't have the time to do this now
