### ISSUE TITLE
[Feature request] - Possibility to change default settings

### ISSUE THREAD

**Issue by griefrelayer** [mirsadm/motioncam#34]
Hello! I'm enjoying this very lovely app of yours. But i want to request you to add the possibility to change default settings for the photos, like in burst mode, but make it default for every photo in every mode. Because the defaults, for example, are not good for my phone as i'm having issues with blue color and desaturation and i can take nice photo only in burst mode after editing it with sliders. I want to have a possibility to save the sliders data between different photos(color, sharpening, for example, i'm not talking about exposure and AWB settings). Thank you very much for your app, have a good day!

**Comment by mirsadm** [comment]
This has now been fixed:
https://github.com/mirsadm/motioncam/releases

You can customise the settings per camera outside of burst mode
