### ISSUE TITLE
Can't run on Pixel 4.

### ISSUE THREAD

**Issue by unknow-dev** [mirsadm/motioncam#4]
Hi @mirsadm,

I downloaded MotionCam from Google Play on my Pixel 4, when open it close immediately.

**Comment by mirsadm** [comment]
Hi,
The Play Store version hasn't been updated in a bit. Can you try running this one from the releases page?

https://github.com/mirsadm/motioncam/releases/download/2.1.2/MotionCam-2.1.2.apk

**Comment by unknow-dev** [comment]
I think i same #6. So close it.

Thanks.
