### ISSUE TITLE
GUI - Strings not translated

### ISSUE THREAD

**Issue by bovirus** [mirsadm/motioncam#47]
@mirsadm 

There are some strings to add to strings.xml

AE LOCK
AF LOCK
AWB LOCK
Warning: This is an experimental feature.
Share
Pop (what's this???)
Open
Other
Save DNG file in addition to the JPEG. Only the noise reductionsettings apply to the dng image.
Save DNG
White Point
Blue

The translations are

BLOC. AE
BLOC. AF
BLOC. AWB
Attenzione: è una funzione seprimentale.
Condividi
Pop
Apri
Altro
Salva file DNG in aggiunta al file JPEG. Si applicano all'immagine DNG solo le impostazioni di riduzione del rumore.
Salva DNG
Punti bianchi
Blu

What's the emaning of WARMTH
string name="preview_warmth">WARMTH

Please check screenshots

![Screenshot_2021-12-08-20-20-57-185_com motioncam](https://user-images.githubusercontent.com/1262554/145271292-ac2c4432-774f-4ece-9621-252e7c1cef41.jpg)

**Increase text button width for "COME SCATTO"**

![Screenshot_2021-12-08-20-21-08-343_com motioncam](https://user-images.githubusercontent.com/1262554/145271836-b88a6ec7-9e44-48b2-acbd-6d65f87c7e20.jpg)

**Increase text width for text "Automatica"**
**Increase text width for text "Velocità otturatore"**

Thanks.

**Comment by mirsadm** [comment]
Thanks so much for doing this. I will merge it in soon.
