### ISSUE TITLE
Can't run on Pixel 3

### ISSUE THREAD

**Issue by just-a-user-sudo** [mirsadm/motioncam#6]
Since version 1.6, Motion Cam will crash almost immediately upon startup on the Google Pixel 3. 

Disabling sensors through developer settings will let Motion Cam run (but that disables the camera so the app wouldn't be useful).

https://user-images.githubusercontent.com/80051348/109980375-d6463f80-7ccd-11eb-866d-dbbf41e5c54f.mp4

**Comment by mirsadm** [comment]
Thanks for the report. It seems the Pixel 3 doesn't support OpenCL for whatever reason. I'll need to figure out a way around that.

**Comment by mirsadm** [comment]
@just-a-user-sudo This should be fixed in 2.5 release here:
https://github.com/mirsadm/motioncam/releases/download/2.5/MotionCam-2.5.apk
