### ISSUE TITLE
8.0.0-beta0 issues

### ISSUE THREAD

**Issue by miestopaukstis** [mirsadm/motioncam#63]
Hi, thanks for big update, here's few issues i've noticed using Mi 11 Ultra:
- OIS toggle dissapeared
- Crop preview tool looks very nice and welcomed, but somehow it seems to be working (or displaying) opposite
- Recorded RAW video are placed not in zip files, but looks like filetype is recoginized like a VIDEOxxxx.container . So external conversion seems not possible with tools that I do have from previous version.

**Comment by 2blackbar** [comment]
you tried unzip it ?

**Comment by mirsadm** [comment]
ZIPs are gone. Unfortunately they were adding too much overhead so its using a custom file format now. It provides a pretty significant boost in write speed.

**Comment by mirsadm** [comment]
Crop is fixed here:
https://github.com/mirsadm/motioncam/releases/download/8.0.0-beta1/MotionCam.8.0.0-beta1.apk
