### ISSUE TITLE
Request ProRes video output format

### ISSUE THREAD

**Issue by hoodFX** [mirsadm/motioncam#66]
Besides being able to export the DNG format, hopefully there will be an additional option to export video to the ProRes 4444 format which is able to compress videos with a depth of 12bit or 10bit.
Just to be more easier for user to edit in any non pro video editor.

**Comment by 2blackbar** [comment]
Good idea for pc converter

**Comment by mirsadm** [comment]
As far as I can tell there's no way for me to support this format without involving Apple in some way.

**Comment by mirsadm** [comment]
Unfortunately I don't think this one is feasible anytime soon so will close this for now
