### ISSUE TITLE
[Feature request] delete source raw video file after CinemaDNG conversion

### ISSUE THREAD

**Issue by nocantsin** [mirsadm/motioncam#68]
It would be really helpful if there was a configuration option that video raw source files (i.e. in Motion Cam's internal format) will get deleted immediately after their CinemaDNG conversion, in order to better deal with storage space limitations. - Alternatively or in addition, it would be great to have an external command line utility for Linux and other operating systems that could do the CinemaDNG conversion on the desktop computer [which would probably be faster, and an alternative way of preventing storage space issues on the phone].

**Comment by 2blackbar** [comment]
yup , in settings as option

**Comment by nocantsin** [comment]
Has been resolved with 8.0.0-beta3 - thank you so much!
