### ISSUE TITLE
[RAW Video] Ability to set custom RAM usage limit

### ISSUE THREAD

**Issue by epicfilmmaker93** [mirsadm/motioncam#72]
With new devices that have 12GB or even more RAM it would be great to have an input field instead of a limited slider to change the memory usage limit

**Comment by 2blackbar** [comment]
Its all about your internal sd card writing speed, it varies from 40MBs to 440MBs on different phones that i have so run SD BENCH on yout phone to determine your speed or just get SSD, you wont get frame drops . For 4k in cinemascope ratio you would need about 150-170MB of speed
