### ISSUE TITLE
[Feature request] compile convert tool too

### ISSUE THREAD

**Issue by FilipZamec** [mirsadm/motioncam#75]
Phones get pushed a lot with these huge file sizes. 
One thing how to help is to convert files to dng on PC. 
Would it be possible to give us that convert utility compiled, so we can use it?
I got it in previous versions and it's a big help.

Thank you 🙂

**Comment by experimentator1709** [comment]
We are waiting for the utility for converting to Windows PC. converting on a smartphone is a pain!

**Comment by FilipZamec** [comment]
Yes, that would be even better, but convert utility already exists and we don't have to wait to dedicated Windows one 🙂

**Comment by 2blackbar** [comment]
how its called?

**Comment by FilipZamec** [comment]
The file is called Convert. You can run it on Linux.

**Comment by experimentator1709** [comment]
I was talking about Windows. I and many others are not good at Linux. Also, how does the conversion utility deal with the new VIDEO _ *. Container format?

**Comment by FilipZamec** [comment]
I have Windows too. It was recommended to me, that I could use Ubuntu shell from Windows store and it works fine.
New container doesn't work with the old conversion tool I have, that's why I want the actual tool 🙂

**Comment by experimentator1709** [comment]
Fine. But your case is not everyone's case. To be popular, an application needs to be friendly. However, the developer promised a conversion utility for Windows.

**Comment by newillusion** [comment]
I take participation at this feature request.
I think, a faster way to operatae with .container video is to copy it on a PC and make convertation on the PC.
On my phone (Samsung Note8), converation performs very slow.

**Comment by mirsadm** [comment]
I'm going to close this, Windows & Mac tools are available now
