### ISSUE TITLE
There's no support for CaptureResult ColorCorrectionTransform

### ISSUE THREAD

**Issue by eszdman** [mirsadm/motioncam#8]
On some devices(always undersaturated if wrongly choosed) color correction transform from capture result provides better color accuracy than one from CameraCharacteristics, suggest to add it in dev settings
Wrong matrices for example
![IMG_20210331_083659.jpg](https://user-images.githubusercontent.com/45270494/113095536-475d1200-91fc-11eb-9d4f-7004a685208a.jpg)

**Comment by mirsadm** [comment]
That's interesting. On my device it is not included in the capture result. I'll see if I can change it to prefer the capture result if it's there otherwise fallback camera one.

**Comment by eszdman** [comment]
It's better to prefer most saturated one, for better compatibility

**Comment by mirsadm** [comment]
This should be fixed now. Have not build a new APK yet though
