### ISSUE TITLE
Can your processing work on bayer data from non-android system?

### ISSUE THREAD

**Issue by f0enix** [mirsadm/motioncam#9]
Hi,
I have been doing some work on raw CFA data coming from raspberry pi having Sony camera sensors. I have used libraw/dcraw in the past to get previewable image from such data. I came across your repository and it seems that you are using Halide for real time demosaicing and image stacking for noise reduction which i find interesting.

I tried creating a metadata file containing information of the `RGGB` bayer along with raw bayer files and feed it to your algorithm but the output is messed up. It seems a channel/color issue. So my question is that whether your implementation is only specific to Android bayer data?

Here is my metadata file:
```json
{
    "colorIlluminant2": "standarda",
    "whiteLevel": 1095,
    "colorMatrix1": [1.506935715675354, -0.8880840539932251, -0.13350626826286316, -0.53555202484130859, 1.5421112775802612, 0.1474035233259201, -0.019240813329815865, 0.095311708748340607, 0.76038378477096558],
    "apertures": [1.6959937810599961],
    "colorMatrix2": [0.82994842529296875, -0.27388653159141541, -0.097103022038936615, -0.57290846109390259, 1.3635042905807495, 0.17090092599391937, -0.086338728666305542, 0.13636419177055359, 0.53642231225967407],
    "sensorArrangment": "rggb",
    "forwardMatrix2": [],
    "blackLevel": [64, 64, 64, 64],
    "focalLengths": [4],
    "colorIlluminant1": "d65",
    "writeDNG": true,
    "frames": [{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame0.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame1.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame2.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame3.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame4.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame5.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame6.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    },{
        "exposureTime": 333333333.33333331,
        "orientation": 0,
        "timestamp": "1598542181000000",
        "filename": "frame7.raw",
        "asShotNeutral": [0.49100935459136963, 1, 0.4330725371837616],
        "width": 4032,
        "rowStride": 4032,
        "height": 3024,
        "colorCorrectionGains": [0, 0, 0, 0],
        "lensShadingMapHeight": 0,
        "lensShadingMapWidth": 0,
        "iso": 800
    }],
    "referenceTimestamp": "1598542181000000",
    "pixelFormat": "raw10",
    "postProcessingSettings": {
        
    },
    "forwardMatrix1": []
}
```

Note that i did not have information about the `rowStride` so i set it same as the width.
Since i don't have the lensShadingMap data, i set `lensShadingMapHeight` and `lensShadingMapWidth` to 0. This is what the final output image looks like:
<img width="798" alt="Screenshot 2021-04-14 at 15 14 01" src="https://user-images.githubusercontent.com/72214428/114701620-19b3b500-9d34-11eb-893e-a1183a223d2f.png">

Is the above json enough for the algorithm to work with or does it need additional metadata?

**Comment by mirsadm** [comment]
It's hard to say. The metadata you've constructed is set to use RAW10 which is an Android specific format (https://developer.android.com/reference/android/graphics/ImageFormat#RAW10). Is it stored as 16 bits per pixel instead? If that's the case you can change the RAW10 to RAW16. The row stride is in bytes which should be set to width * (10 / 8) if using RAW10 or width * (16 / 8) if RAW 16.

**Comment by mirsadm** [comment]
If you are able to send me the full file (frames + metadata you've constructed + some information about the camera) I can give it a go as well.

**Comment by f0enix** [comment]
Thanks for the quick reply. Yes it is stored in 16 bits (i was not getting good results so i tried playing with the pixel format). Switching to `raw16` and using the correct `rowStride` improved the result but it is still pink
![Screenshot 2021-04-14 at 20 21 41](https://user-images.githubusercontent.com/72214428/114745504-c48d9880-9d5f-11eb-808d-0e9f223607e2.png)

I currently do not have the camera on hand (due to it being in my office drawer and currently due to lockdown, don't know when i'll be able to bring it back). It is a small camera for embedded systems similar to the Sony IMX477 model but it allows capturing RGGB bayer. I had been capturing a lot of these raw data for analysis in the past and this is what i am currently using to experiment on libmotioncam.

Here is the link to the sample zip that i feed to the program:
[https://easyupload.io/rgtxt9](https://easyupload.io/rgtxt9)

**Comment by mirsadm** [comment]
Hey @f0enix,

I had a quick look and there was a simple error in the metadata. The pixelFormat is stored per frame at the moment. Additionally, I've modified the black/white levels. It will probably need additional tweaking, here's the output:

![Archive](https://user-images.githubusercontent.com/508688/114863135-44ab1100-9de7-11eb-91b9-8879c8dd5ea1.jpg)

And the metadata:

```
{
  "colorIlluminant2": "standarda",
  "whiteLevel": 16383,
  "colorMatrix1": [
    1.506935715675354,
    -0.8880840539932251,
    -0.13350626826286316,
    -0.53555202484130859,
    1.5421112775802612,
    0.1474035233259201,
    -0.019240813329815865,
    0.095311708748340607,
    0.76038378477096558
  ],
  "apertures": [
    1.6959937810599961
  ],
  "colorMatrix2": [
    0.82994842529296875,
    -0.27388653159141541,
    -0.097103022038936615,
    -0.57290846109390259,
    1.3635042905807495,
    0.17090092599391937,
    -0.086338728666305542,
    0.13636419177055359,
    0.53642231225967407
  ],
  "sensorArrangment": "bggr",
  "forwardMatrix2": [],
  "blackLevel": [
    2127,
    2127,
    2127,
    2127
  ],
  "focalLengths": [
    4
  ],
  "colorIlluminant1": "d65",
  "writeDNG": true,
  "frames": [
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame0.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame1.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame2.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame3.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame4.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame5.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame6.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    },
    {
      "exposureTime": 333333333.33333331,
      "orientation": 0,
      "timestamp": "1598542181000000",
      "filename": "frame7.raw",
      "asShotNeutral": [
        0.49100935459136963,
        1,
        0.4330725371837616
      ],
      "width": 4032,
      "rowStride": 8064,
      "height": 3024,
      "colorCorrectionGains": [
        0,
        0,
        0,
        0
      ],
      "lensShadingMapHeight": 0,
      "lensShadingMapWidth": 0,
      "iso": 800,
      "pixelFormat": "raw16"
    }
  ],
  "referenceTimestamp": "1598542181000000",
  "pixelFormat": "raw16",
  "postProcessingSettings": {},
  "forwardMatrix1": []
}
```

**Comment by f0enix** [comment]
> The pixelFormat is stored per frame at the moment

I was assuming that it would be stored at global level since all frames are most likely to have same pixel format.

I tried your modified metadata and on mine the results look slight different with a green tint instead.
<img width="666" alt="Screenshot 2021-04-15 at 17 20 27" src="https://user-images.githubusercontent.com/72214428/114876462-69b37a00-9e0f-11eb-8186-5f04a5482aa0.png">

I am currently using the latest version on master. 

Furthermore i found that the dng generated is corrupted and cannot be opened in Photoshop/Lightroom but is working on RawDigger/RawTherapee. Not sure if you are aware of it but just wanted to point it out.
<img width="532" alt="Screenshot 2021-04-15 at 17 38 28" src="https://user-images.githubusercontent.com/72214428/114878557-6d480080-9e11-11eb-8b27-4c103d1880ed.png">

**Comment by mirsadm** [comment]
In the metadata I posted above I had changed the sensorArrangement to BGGR as a test. You'd want to change that back to RGGB.

I don't have Lightroom to test with on my Mac but I am able to open the DNGs generated by the Android app in the mobile version of Lightroom. It may be because of the missing lens shading map or something along those lines that it's failing to open that particular DNG.

Is the image I posted correct? I can't tell if the colours are accurate.

**Comment by f0enix** [comment]
I changed to it RGGB and the result is much better. If i open the dng in mac quick preview, it looks close to the original photo but the jpg version has strong red tint. Here is the comparison:
![Screenshot 2021-04-15 at 18 32 53](https://user-images.githubusercontent.com/72214428/114887183-42fa4100-9e19-11eb-995a-0ed7b7347894.png)

![Screenshot 2021-04-15 at 18 33 09](https://user-images.githubusercontent.com/72214428/114887223-4beb1280-9e19-11eb-9460-27e83849c938.png)

I don't have an exact rgb version of that raw bayer because i had been applying some post processing settings on it. But to give you an idea, here is how it looked like with those settings:
<img width="686" alt="Screenshot 2021-04-15 at 18 32 27" src="https://user-images.githubusercontent.com/72214428/114887414-7dfc7480-9e19-11eb-926b-e5e24715ab48.png">

Maybe the red tint has something to do with the XYZ mapping from the camera colorspace to the srgb colorspace or is it a white balance issue?

**Comment by mirsadm** [comment]
You are right. The missing forward matrix was causing it to miscalculate the sRGB matrix. I've pushed a fix. Here's the output now:

![Archive zip](https://user-images.githubusercontent.com/508688/114899772-2a832a00-9e0b-11eb-8385-840eae4fd72a.jpg)

**Comment by f0enix** [comment]
Now it looks good.

Btw i just tried to convert a raw frame to srgb using the `createPreview` method. I used a downscaling of 2 and was expecting it to result in an image of `1512x2016` px but instead the result was `756x1008` px. It seems that it is apply a double downscaling. Is this the expected behaviour?

```c++
auto frame = rawContainer.loadFrame(*it);
Halide::Runtime::Buffer<uint8_t>framePreview = createPreview(*frame, 2, rawContainer.getCameraMetadata(),rawContainer.getPostProcessSettings());
cv::Mat framePreviewImg(framePreview.height(),framePreview.width(),CV_8UC4,framePreview.data());
cv::cvtColor(framePreviewImg, framePreviewImg, cv::COLOR_BGRA2RGBA);
cv::imwrite("preview.jp", framePreviewImg);
```

**Comment by mirsadm** [comment]
Yep, I use that mostly to create a fast preview in the Android app. It is a rough estimate of the full post processing. The reason is that the preview code is simply averaging the green channels and not demosaicing to a full sized image. So without downscaling it'll already be half the width and height.

**Comment by f0enix** [comment]
ok thanks
