### ISSUE TITLE
The camera can't see anything since 8.0.0-beta0

### ISSUE THREAD

**Issue by mido830** [mirsadm/motioncam#91]
I use Sony Xperia 5 II.
This is how the app looked like since 7.0 to 7.0.8-beta5:
![7 0](https://user-images.githubusercontent.com/16670034/147405832-e8adc210-4cc8-4d90-818b-c0b842ce28c0.png)

This is how it looks like since 8.0.0-beta0:
![8 0 3](https://user-images.githubusercontent.com/16670034/147405856-1ffbb7e6-080b-4b9c-870d-ecef14c41039.png)

It's just not that the preview doesn't work, the camera can't capture anything at all, be it photos or videos.

**Comment by mirsadm** [comment]
Could you try selecting RAW16 or RAW10 in the settings to see if it changes anything?

**Comment by mido830** [comment]
> Could you try selecting RAW16 or RAW10 in the settings to see if it changes anything?

Just tested, no difference.

**Comment by mirsadm** [comment]
Could you give this one a go please:
https://github.com/mirsadm/motioncam/releases/download/8.0.3/MotionCam.8.0.3.apk

**Comment by mido830** [comment]
> Could you give this one a go please: https://github.com/mirsadm/motioncam/releases/download/8.0.3/MotionCam.8.0.3.apk

I tested all releases, this one included. Not a single release work for me since 8.0.0-beta0

**Comment by mirsadm** [comment]
hmm I'd need some logs from ADB to figure out what's going on. Have you also tried uninstalling and installing it again so it resets all the settings?

**Comment by mido830** [comment]
> hmm I'd need some logs from ADB to figure out what's going on.

How do I generate them? Max I was using ADB for was removing bloatware.

**Comment by mirsadm** [comment]
https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/

Basically this line:
>adb logcat -v long > logs.txt

Run then run the app maybe switch cameras and exit. The logs should be in logs.txt

**Comment by mido830** [comment]
[logs.txt](https://github.com/mirsadm/motioncam/files/7776959/logs.txt)

**Comment by mirsadm** [comment]
Thanks for the logs. I think I've narrowed down the change since then. Here's another release:
https://github.com/mirsadm/motioncam/releases/download/8.0.4/MotionCam.8.0.4.apk

**Comment by mido830** [comment]
Fixed in 8.0.4.
